language: node_js
cache: yarn
node_js:
  - "10"
before_install:
  - if [ -n "$TRAVIS_TAG" ]; then export TAG=$TRAVIS_TAG; fi
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn install
script:
  - yarn vscode:prepublish
  - yarn lint
after_success:
  - chmod +x scripts/publish.sh
  - if [ -n "$TRAVIS_TAG" ]; then scripts/publish.sh; fi
